# Generated by Django 5.2.17 on 2026-08-14 05:04
from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("chat", "0002_chatmessage_parent_confidence_and_more"),
    ]

    operations = []