# Generated by Django 5.2.17 on 2026-08-14 05:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("chat", "0004_merge_20260814_1404"),
        ("topics", "0002_searchhistory"),
    ]

    operations = [
        migrations.AlterField(
            model_name="chatsession",
            name="knowledge_node",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="chat_sessions_for_node",
                to="topics.knowledgenode",
            ),
        ),
    ]
