# Generated by Django 5.2.17 on 2026-08-12 06:47

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Topic',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('position', models.PositiveIntegerField(default=0, help_text='UI上でのブランチ(枝)の表示順序')),
                ('parent', models.ForeignKey(blank=True, help_text='None の場合はルートトピック', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='topics.topic')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='topics', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['position', 'created_at'],
            },
        ),
        migrations.CreateModel(
            name='KnowledgeNode',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(help_text='概念の簡潔な要約', max_length=255)),
                ('content', models.TextField(help_text='課題本文 / プレーンテキスト形式の標準解答')),
                ('origin_node', models.ForeignKey(blank=True, help_text='間隔復習機能でAIが類題として生成した場合、元になったノード', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='generated_nodes', to='topics.knowledgenode')),
                ('topic', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='knowledge_nodes', to='topics.topic')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
