# Generated by Django 5.2.17 on 2026-08-14 08:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('topics', '0002_remove_knowledgenode_origin_node'),
        ('topics', '0002_searchhistory'),
    ]

    operations = [
    ]
